-- 코드를 입력하세요
SELECT b.AUTHOR_ID,
       a.AUTHOR_NAME,
       b.CATEGORY,
       SUM(s.sales * b.price) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a
  ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES s
  ON b.BOOK_ID = s.BOOK_ID
WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC;