WITH TOTAL AS (
    SELECT DISTINCT USER_ID
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)

SELECT YEAR(SALES_DATE) AS 'YEAR'
      ,MONTH(SALES_DATE) AS 'MONTH'
      ,COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
      ,ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM TOTAL), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (
    SELECT *
    FROM TOTAL
)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC