-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT * p.PRICE) TOTAL_SALES
from FOOD_PRODUCT p
join FOOD_ORDER o
on p.PRODUCT_ID = o.PRODUCT_ID
where substring(o.PRODUCE_DATE,1,7) = '2022-05'
GROUP BY p.PRODUCT_ID
order by TOTAL_SALES desc, p.PRODUCT_ID