SELECT 
    h.HISTORY_ID,
    FLOOR(
        CASE 
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN
                c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * (100 - d90.DISCOUNT_RATE) / 100
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN
                c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * (100 - d30.DISCOUNT_RATE) / 100
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN
                c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * (100 - d7.DISCOUNT_RATE) / 100
            ELSE
                c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1)
        END
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d7 ON c.CAR_TYPE = d7.CAR_TYPE AND d7.DURATION_TYPE = '7일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d30 ON c.CAR_TYPE = d30.CAR_TYPE AND d30.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d90 ON c.CAR_TYPE = d90.CAR_TYPE AND d90.DURATION_TYPE = '90일 이상'
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, h.HISTORY_ID DESC;